from django.db import models
from curriculum.models import SubStrand
from resources.models import Material

class LessonPlan(models.Model):
    STATUS_CHOICES = (
        ('DRAFT', 'Draft'),
        ('GENERATED', 'AI Generated'),
        ('APPROVED', 'Approved'),
    )

    title = models.CharField(max_length=255)
    substrand = models.ForeignKey(SubStrand, on_delete=models.CASCADE, related_name='lesson_plans')
    reference_material = models.ForeignKey(Material, on_delete=models.SET_NULL, null=True, blank=True)
    
    # The content generated by AI. 
    # We use JSONField to store the structured lesson plan (Objectives, Activities, etc.)
    content = models.JSONField(default=dict) 
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='GENERATED')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): return self.title