# Generated by Django 6.0.3 on 2026-03-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('grades', models.ManyToManyField(related_name='learning_areas', to='curriculum.grade')),
            ],
            options={
                'verbose_name': 'Learning Area',
                'verbose_name_plural': 'Learning Areas',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.grade')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curriculum.learningarea')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('suggested_duration', models.PositiveIntegerField(default=1, help_text='Duration in hours')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substrands', to='curriculum.strand')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. 4.1.1', max_length=50)),
                ('description', models.TextField()),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='curriculum.substrand')),
            ],
        ),
    ]
