# Generated by Django 6.0.3 on 2026-03-05 13:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the content')),
                ('material_type', models.CharField(choices=[('NOTE', 'Summarized Note'), ('REVISION', 'Revision Material'), ('SCHEME', 'Scheme of Work')], default='NOTE', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('learning_outcomes', models.ManyToManyField(blank=True, related_name='materials', to='curriculum.learningoutcome')),
                ('substrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='curriculum.substrand')),
                ('tags', models.ManyToManyField(blank=True, to='resources.tag')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
